<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CRUD Testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>38141b21-a45e-4b5b-bb54-59748c709e76</testSuiteGuid>
   <testCaseLink>
      <guid>0027545f-901c-4f73-870c-462b88e7787e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PaymentGatewayCRUD_TC/TC_001_Create_Payment_Gateway</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>309fb2a3-0e02-4d59-8d64-3cb3545e9ae0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CRUDTestData/CRUD Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>309fb2a3-0e02-4d59-8d64-3cb3545e9ae0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>bc275302-4107-46d6-90e5-88f248d86933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76579712-4a68-4f1d-91c2-116df04beffe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30ec1b04-b1a4-40f3-9a4a-bdf9041cb247</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PaymentGatewayCRUD_TC/TC_002_Update_Payment_Gateway</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e074239b-0d3b-4efc-95ec-edaebc892c1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a50e71bf-1419-4f29-8dc9-ce1b1f6f6983</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67d920a8-fff6-4e6f-8e45-6334e40edd58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PaymentGatewayCRUD_TC/TC_003_Delete_Payment_Gateway</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33479186-3580-42d3-8c0f-14c1c38feb20</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
