<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>AddPaymentGateway</name>
   <tag></tag>
   <elementGuidId>74af6fe9-2777-4f62-8c77-0a8c4d410d87</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;paymentGatewayProviderId\&quot;: ${PaymentGatewayProId},\n  \&quot;name\&quot;: \&quot;${PaymentGatewayName}\&quot;,\n  \&quot;profileId\&quot;: \&quot;${ProfileID}\&quot;,\n  \&quot;accessKey\&quot;: \&quot;${AccessKey}\&quot;,\n  \&quot;secretKey\&quot;: \&quot;${SecretKey}\&quot;,\n  \&quot;onboardUrl\&quot;: \&quot;${OnboardURL}\&quot;,\n  \&quot;onboardFinishUrl\&quot;: \&quot;${OnboardFinishURL}\&quot;,\n  \&quot;onboardCancelledUrl\&quot;: \&quot;${OnboardCancelledURL}\&quot;,\n  \&quot;onboardErrorUrl\&quot;: \&quot;${OnboardErrorURL}\&quot;,\n  \&quot;apiEndpoint\&quot;: \&quot;${APIEndpoint}\&quot;,\n  \&quot;onboardTimeout\&quot;: ${OnboardTimeout},\n  \&quot;maximumCardAllowed\&quot;: ${MaximumCardAllowed},\n  \&quot;masterMerchantId\&quot;: \&quot;${MasterMerchantID}\&quot;,\n  \&quot;masterMerchantKeyFileName\&quot;: \&quot;${MMKeyFile}\&quot;,\n  \&quot;defaultCountry\&quot;: ${DefaultCountry},\n  \&quot;defaultCurrency\&quot;: ${DefaultCurrency},\n  \&quot;isAvailable\&quot;: ${isAvailable},\n  \&quot;logo\&quot;: \&quot;${Logo}\&quot;,\n  \&quot;clientId\&quot;: \&quot;${ClientID}\&quot;,\n  \&quot;onboardingMethod\&quot;: \&quot;${OnboardingMethod}\&quot;,\n  \&quot;excludeLoyalty\&quot;: ${ExcludeLoyalty},\n  \&quot;preauthAmount\&quot;: ${PreAuthAmount},\n  \&quot;configurationKey\&quot;: \&quot;${ConfigurationKey}\&quot;,\n  \&quot;acquirerId\&quot;: \&quot;${AcquirerID}\&quot;,\n  \&quot;cardPrefix\&quot;: \&quot;${CardPrefix}\&quot;,\n  \&quot;cardLogos\&quot;: [\n    {\n      \&quot;id\&quot;: 1,\n      \&quot;cardName\&quot;: \&quot;string\&quot;,\n      \&quot;cardType\&quot;: \&quot;string\&quot;,\n      \&quot;logo\&quot;: \&quot;string\&quot;,\n      \&quot;acceptanceLogo\&quot;: \&quot;string\&quot;\n    }\n  ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>http://localhost:1203/api/v1/payment/payment-gateway</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>1</defaultValue>
      <description></description>
      <id>9af1ce79-dd08-4394-b784-ae1750c593ee</id>
      <masked>false</masked>
      <name>PaymentGatewayProId</name>
   </variables>
   <variables>
      <defaultValue>'Cybersource - SG'</defaultValue>
      <description></description>
      <id>9cd9c604-9275-400c-8799-2bea423aafde</id>
      <masked>false</masked>
      <name>PaymentGatewayName</name>
   </variables>
   <variables>
      <defaultValue>'19ACF053-363F-41B2-80C6-B95012AA3A31'</defaultValue>
      <description></description>
      <id>e5b235a2-f34f-4ded-8fe5-ed0f4a6870d2</id>
      <masked>false</masked>
      <name>ProfileID</name>
   </variables>
   <variables>
      <defaultValue>'7fddb35cc1ee3cf1964e1e419844bc9f'</defaultValue>
      <description></description>
      <id>bbcbde53-3b91-4fe4-bc35-b04a9767ae54</id>
      <masked>false</masked>
      <name>AccessKey</name>
   </variables>
   <variables>
      <defaultValue>'bc11a1bef8b0408690fa4667e4caca788ddd5631067a4c48afd2ce059b095ee96aa343a7669b45e0b6c1302664f8f23f1cfa5e4d1991473598838e6503515ea4422ba57996974d6795cf2a8f0a542de31199e3acd21440cfb80559005520cd5acfa31163260746e6882ed496a2d91228aae98fe6c9054e7f82211608bdc6a05a'</defaultValue>
      <description></description>
      <id>342b3046-469e-42c1-8fa3-fd54709e103c</id>
      <masked>false</masked>
      <name>SecretKey</name>
   </variables>
   <variables>
      <defaultValue>'https://testsecureacceptance.cybersource.com/pay '</defaultValue>
      <description></description>
      <id>066205c6-62c4-4237-9ca8-26aa177a6e12</id>
      <masked>false</masked>
      <name>OnboardURL</name>
   </variables>
   <variables>
      <defaultValue>'https://risingstar.strateqgroup.com/PaymentProfile/Finish?Gateway=1&amp;locale={0}'</defaultValue>
      <description></description>
      <id>ffd13c40-5a7b-4c71-b691-71cd2eeaf814</id>
      <masked>false</masked>
      <name>OnboardFinishURL</name>
   </variables>
   <variables>
      <defaultValue>'NULL'</defaultValue>
      <description></description>
      <id>23439feb-fca1-44eb-81bb-a87371bf39d9</id>
      <masked>false</masked>
      <name>OnboardCancelledURL</name>
   </variables>
   <variables>
      <defaultValue>'NULL'</defaultValue>
      <description></description>
      <id>5b9a9663-f791-421e-8a03-9e5288aed7cc</id>
      <masked>false</masked>
      <name>OnboardErrorURL</name>
   </variables>
   <variables>
      <defaultValue>'abc'</defaultValue>
      <description></description>
      <id>98533f36-cc75-4ef7-8c73-1fe3514ad727</id>
      <masked>false</masked>
      <name>APIEndpoint</name>
   </variables>
   <variables>
      <defaultValue>250</defaultValue>
      <description></description>
      <id>b948c6ee-176b-4d5d-a608-9d97aae94ddd</id>
      <masked>false</masked>
      <name>OnboardTimeout</name>
   </variables>
   <variables>
      <defaultValue>4</defaultValue>
      <description></description>
      <id>6ed2dd5a-33ed-46d5-befa-ef9018c0b842</id>
      <masked>false</masked>
      <name>MaximumCardAllowed</name>
   </variables>
   <variables>
      <defaultValue>'gpsgh065004547701'</defaultValue>
      <description></description>
      <id>e965ab67-8ac3-46f6-b893-742ec63e938d</id>
      <masked>false</masked>
      <name>MasterMerchantID</name>
   </variables>
   <variables>
      <defaultValue>'C:/fakepath/gpsgh065004547701.p12'</defaultValue>
      <description></description>
      <id>eb3bbac8-e28b-4165-a810-428c936fa91b</id>
      <masked>false</masked>
      <name>MMKeyFile</name>
   </variables>
   <variables>
      <defaultValue>195</defaultValue>
      <description></description>
      <id>9a6db2d7-3bc5-4a43-9763-6919baf418fb</id>
      <masked>false</masked>
      <name>DefaultCountry</name>
   </variables>
   <variables>
      <defaultValue>92</defaultValue>
      <description></description>
      <id>89967af4-15b4-4f44-8451-a8c6262afa1b</id>
      <masked>false</masked>
      <name>DefaultCurrency</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>9c76730f-a43d-40f0-bf44-d7c52960e5bc</id>
      <masked>false</masked>
      <name>isAvailable</name>
   </variables>
   <variables>
      <defaultValue>'Logo'</defaultValue>
      <description></description>
      <id>ab4f56ae-3b98-4ffa-b922-4cdfc2a385a0</id>
      <masked>false</masked>
      <name>Logo</name>
   </variables>
   <variables>
      <defaultValue>' asdsa'</defaultValue>
      <description></description>
      <id>3b88057b-201a-412f-aac2-91167368f3df</id>
      <masked>false</masked>
      <name>ClientID</name>
   </variables>
   <variables>
      <defaultValue>'POST'</defaultValue>
      <description></description>
      <id>3ca41536-c9a8-432f-bd51-a7cbf856597e</id>
      <masked>false</masked>
      <name>OnboardingMethod</name>
   </variables>
   <variables>
      <defaultValue>false</defaultValue>
      <description></description>
      <id>5f5708c6-5c94-4368-b03d-b5cac202d53d</id>
      <masked>false</masked>
      <name>ExcludeLoyalty</name>
   </variables>
   <variables>
      <defaultValue>0</defaultValue>
      <description></description>
      <id>d29c2812-66bf-4bc4-b1c7-d6f5e97970f0</id>
      <masked>false</masked>
      <name>PreAuthAmount</name>
   </variables>
   <variables>
      <defaultValue>'NULL'</defaultValue>
      <description></description>
      <id>5779f03e-90fd-40aa-9385-3150ca097fa8</id>
      <masked>false</masked>
      <name>ConfigurationKey</name>
   </variables>
   <variables>
      <defaultValue>'APP1'</defaultValue>
      <description></description>
      <id>c99a1048-d9e6-4399-8b3f-87a0dbe04cc6</id>
      <masked>false</masked>
      <name>AcquirerID</name>
   </variables>
   <variables>
      <defaultValue>'NULL'</defaultValue>
      <description></description>
      <id>7d215419-323c-4cce-8282-e4eae123b588</id>
      <masked>false</masked>
      <name>CardPrefix</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
